In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/game-of-thrones-book-dataset/4 - A Feast for Crows.txt
/kaggle/input/game-of-thrones-book-dataset/3 - A Storm of Swords.txt
/kaggle/input/game-of-thrones-book-dataset/5 - A Dance with Dragons.txt
/kaggle/input/game-of-thrones-book-dataset/2 - A Clash of Kings.txt
/kaggle/input/game-of-thrones-book-dataset/1 - A Game of Thrones.txt


In [2]:
pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 42.9 MB/s eta 0:00:00
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
nilearn 0.11.1 requires scikit-learn>=1.4.0, but you have scikit-learn 1.2.2 which is incompatible.
bigframes 1.36.0 requires rich<14,>=12.4.4, but you have rich 14.0.0 which is incompatible.
imbalanced-learn 0.13.0 requires scikit-learn<2,>=1.3.2, but you have scikit-learn 1.2.2 which is incompatible.
plotnine 0.14.5 requires matplotlib>=3.8.0, but you have matplotlib 3.7.5 which is incompatible.


In [3]:
import gensim
import os

In [4]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [5]:
story = []

data_path = '/kaggle/input/game-of-thrones-book-dataset'

for filename in os.listdir(data_path):
    file_path = os.path.join(data_path, filename)

    if os.path.isfile(file_path) and filename.endswith('.txt'):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                corpus = f.read()
        except UnicodeDecodeError:
            with open(file_path, 'r', encoding='windows-1252') as f:
                corpus = f.read()

        raw_sent = sent_tokenize(corpus)

        for sent in raw_sent:
            story.append(simple_preprocess(sent))

In [6]:
len(story)

145020

In [7]:
model = gensim.models.Word2Vec(
    window = 10, #dono side 10 10 words lenge
    min_count = 2,#atleast 2 words
    workers = 4
)

In [8]:
model.build_vocab(story)

In [9]:
model.train(story, total_examples=model.corpus_count,epochs=model.epochs)

(6569946, 8628190)

In [10]:
model.wv.most_similar('daenerys')

[('stormborn', 0.7793377637863159),
 ('targaryen', 0.7573890089988708),
 ('unburnt', 0.7101500034332275),
 ('queen', 0.6859588027000427),
 ('princess', 0.6724908351898193),
 ('margaery', 0.6665481328964233),
 ('myrcella', 0.665920615196228),
 ('elia', 0.6569793224334717),
 ('viserys', 0.6526392698287964),
 ('rhaegar', 0.6369299292564392)]

In [11]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [12]:
model.wv['king']

array([ 3.5852847 ,  0.20297706,  2.0511765 ,  0.8044171 , -3.0723555 ,
        0.92368776,  0.19184111,  1.5680051 , -0.5405523 ,  1.6693158 ,
       -1.93851   ,  0.25638938, -0.19444959,  2.0078099 , -3.0804143 ,
       -0.34006235,  0.85916424,  2.4446955 ,  0.91292113,  4.4111214 ,
       -2.08685   , -0.6247825 ,  0.47868344,  0.3109943 , -1.2503558 ,
        0.4912548 ,  1.0637527 , -0.09928966, -0.8940467 ,  3.0026689 ,
       -0.6874027 ,  1.7539895 ,  1.0101954 , -0.37055495,  0.47773448,
       -4.2889113 , -1.3280537 , -0.37104875,  0.6919698 , -3.7290792 ,
        1.3120883 ,  0.7421559 ,  2.5119708 ,  0.53439766,  0.19928966,
       -1.9082675 , -0.4261913 , -4.8343644 ,  3.756245  , -1.6760336 ,
       -2.9603584 , -2.2591915 , -0.07407916, -3.4774663 ,  3.1703272 ,
       -1.3843559 , -0.5906429 ,  0.91988164,  2.298345  ,  2.041453  ,
        1.5693115 ,  3.2165399 ,  1.7183274 ,  1.4672369 ,  0.58616954,
        0.9270128 , -2.0958736 , -1.1015282 , -2.8586414 , -0.83

In [13]:
model.wv.similarity('arya','sansa')

0.8713826

In [14]:
model.wv.get_normed_vectors()

array([[-0.01811211, -0.10493182,  0.04184331, ..., -0.29015583,
        -0.01252767,  0.12682399],
       [-0.00985847, -0.10274538,  0.07557677, ..., -0.03553822,
        -0.13169396,  0.0472674 ],
       [ 0.22967468,  0.01071357, -0.11362183, ..., -0.07201519,
         0.1270311 , -0.21977694],
       ...,
       [ 0.16789477,  0.07107531,  0.067128  , ...,  0.11838757,
        -0.20925397, -0.14778942],
       [ 0.07069734,  0.23356156,  0.13055292, ...,  0.06936061,
        -0.08467735, -0.07197778],
       [-0.10694148,  0.00504531, -0.05303301, ..., -0.15029779,
        -0.15830544,  0.02509715]], dtype=float32)

In [15]:
model.wv.get_normed_vectors().shape

(17453, 100)

In [16]:
y = model.wv.index_to_key

In [17]:
len(y)

17453

In [18]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 3)

X = pca.fit_transform(model.wv.get_normed_vectors())

In [19]:
X[:5]

array([[-0.16444434,  0.5834611 , -0.02081925],
       [-0.16572241,  0.3417992 ,  0.06922016],
       [ 0.29982877,  0.53905976,  0.2580265 ],
       [-0.00699334,  0.3536249 , -0.05687918],
       [ 0.1039352 ,  0.50707436,  0.30987373]], dtype=float32)

In [20]:
X.shape

(17453, 3)

In [21]:
import plotly.express as px

fig  = px.scatter_3d(X[:500],x=0,y=1,z=2,color=y[:500])
fig.show()