In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
X,y = load_diabetes(return_X_y=True)

In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
X.shape

(442, 10)

In [6]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [7]:
y.shape

(442,)

## Using Sklearn's Linear Regression

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [9]:
X_train.shape
X_test.shape

(89, 10)

In [10]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(X_train,y_train)

LinearRegression()

In [11]:
y_pred = reg.predict(X_test)

In [12]:
from sklearn.metrics import r2_score

In [13]:
r2_score(y_test,y_pred)

0.4399338661568969

In [14]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [15]:
reg.intercept_

151.88331005254167

## Making our own Linear Regression Class

In [16]:
class MultipleLinearReg:
    def __int__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X_train, y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        #coefficients
        #NumPy provides the numpy.linalg.inv() function to compute the inverse of a matrix
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)

        self.coef_ = betas[0]
        self.intercept_ = betas[1:]
        print(self.coef_)
        print(self.intercept_)

    
    def predict(self, X_test):
        y_pred = np.dot(X_test, self.coef_) + self.intercept_
        print(y_pred)


In [17]:
X_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [18]:
 np.insert(X_train,0,1,axis=1)

array([[ 1.        , -0.00188202, -0.04464164, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [ 1.        , -0.00914709, -0.04464164, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 1.        ,  0.02354575,  0.05068012, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 1.        ,  0.06350368,  0.05068012, ..., -0.00259226,
         0.08449153, -0.01764613],
       [ 1.        , -0.05273755,  0.05068012, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 1.        ,  0.00175052,  0.05068012, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [19]:
mlr = MultipleLinearReg()

mlr.fit(X_train, y_train)

151.88331005254167
[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]


numpy.insert(arr, obj, values, axis = None)
arr: Input array.
obj: The index before which insertion is to be made.
values: The array of values to be inserted.
axis: The axis along which to insert. If not given then the input array is flattened.

In [20]:
mlr.predict(X_test)

[[ 1.03821723e+00 -2.12234641e+02  5.17224479e+02  3.46033696e+02
  -8.88057883e+02  5.65967574e+02  1.64635805e+02  1.20733011e+02
   8.61034089e+02  5.54030227e+01]
 [-2.10306613e+01 -1.97756857e+02  5.28519894e+02  3.48648254e+02
  -8.83669213e+02  5.71009148e+02  1.57925653e+02  1.26337676e+02
   8.67304525e+02  5.09992043e+01]
 [-2.82383651e+00 -1.97756857e+02  5.14441550e+02  3.38017461e+02
  -8.96417254e+02  5.62495546e+02  1.51774680e+02  1.26449769e+02
   8.59320068e+02  5.28865550e+01]
 [-1.60651636e+01 -2.12234641e+02  5.09366799e+02  3.37667110e+02
  -8.95581316e+02  5.58785708e+02  1.64076626e+02  1.20733011e+02
   8.57360990e+02  5.54030227e+01]
 [-7.78933419e+00 -1.97756857e+02  5.27210280e+02  3.49694077e+02
  -8.92864521e+02  5.57691781e+02  1.46742066e+02  1.31942340e+02
   8.76816095e+02  6.35815425e+01]
 [-3.92728044e+00 -1.97756857e+02  5.35722767e+02  3.44987873e+02
  -9.03731703e+02  5.59261328e+02  1.38354376e+02  1.43151669e+02
   8.61168386e+02  5.66612565e+01

In [21]:
r2_score(y_test,y_pred)

0.4399338661568969

In [22]:
mlr.coef_

151.88331005254167

In [23]:
mlr.intercept_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

NumPy provides the numpy.linalg.inv() function to compute the inverse of a matrix. Let us see how this function works.